spring:
#  sql.init.mode: always # Only for Postgres profile
  jpa:
    show-sql: true
    open-in-view: false
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        jdbc:
          batch_size: 20
        default_batch_fetch_size: 20
        format_sql: true
        enable_lazy_load_no_trans: true

  datasource:
#    H2 DB
    url: jdbc:h2:mem:telros
    username: sa
    password:

#    PostgreSQL
#    url: ${DB_URL}
#    username: ${DB_LOGIN}
#    password: ${DB_PASS}

  jackson:
    visibility:
      field: any
      getter: none
      setter: none
      is-getter: none

logging:
  level:
    root: warn
    com.crevan.telrostesttask: debug
    org.springframework.web.servlet.mvc.method.annotation.ExceptionHandlerExceptionResolver: debug

server.servlet:
  encoding:
    charset: UTF-8
    enabled: true
    force: true
